name: Elixir CI

on:
  repository_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    # env:
    #   DIAGNOSTIC: 1

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16.0'  # [Required] Define the Elixir version
        otp-version: '26.2.2'     # [Required] Define the Erlang/OTP version
        rebar3-version: '3.18.0'
    - name: Compile
      run: |
          rebar3 compile
    - name: Run tests
      run: rebar3 bench
